@ECHO OFF
SET TARGET_DIRECTORY=$(SolutionDir)Release
ECHO [RELEASE] $(TargetFileName) -^> %TARGET_DIRECTORY%
COPY "$(TargetPath)" "%TARGET_DIRECTORY%"


REM @ECHO OFF
REM SET TARGET_PROJECT=BUILDLet.WOLSetup
REM SET TARGET_DIRECTORY=Sources
REM SET TARGET_DIRECTORY=$(SolutionDir)%TARGET_PROJECT%\%TARGET_DIRECTORY%
REM 
REM ECHO [RELEASE] $(TargetFileName) -^> %TARGET_DIRECTORY%
REM COPY "$(TargetPath)" "%TARGET_DIRECTORY%"
