
@ECHO OFF
SET TARGET_DIRECTORY=Release
ECHO [RELEASE] $(TargetFileName) -^> $(SolutionDir)%TARGET_DIRECTORY%
COPY "$(TargetPath)" "$(SolutionDir)%TARGET_DIRECTORY%"

@ECHO OFF
SET TARGET_PROJECT=BUILDLet.WOLSetup
SET TARGET_DIRECTORY=Sources
ECHO [RELEASE] $(TargetFileName) -^> $(SolutionDir)%TARGET_PROJECT%\%TARGET_DIRECTORY%
COPY "$(TargetPath)" "$(SolutionDir)%TARGET_PROJECT%\%TARGET_DIRECTORY%"
