//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUILDLet.Utilities.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUILDLet.Utilities.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ..\..\..\TestData\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryPath_TestData {
            get {
                return ResourceManager.GetString("DirectoryPath_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hello.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_Hello {
            get {
                return ResourceManager.GetString("FileName_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML 4_01 Specification.htm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_HTML_4_01_Specification {
            get {
                return ResourceManager.GetString("FileName_HTML_4_01_Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attributes.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_HTML_AttributeTest {
            get {
                return ResourceManager.GetString("FileName_HTML_AttributeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_HTML_CommentTest {
            get {
                return ResourceManager.GetString("FileName_HTML_CommentTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test1.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_HTML_TestFile1 {
            get {
                return ResourceManager.GetString("FileName_HTML_TestFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test2_STRICT.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_HTML_TestFile2_STRICT {
            get {
                return ResourceManager.GetString("FileName_HTML_TestFile2_STRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   www.tohoho-web.com.how2.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_HTML_ToHoHo_Sample {
            get {
                return ResourceManager.GetString("FileName_HTML_ToHoHo_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tree.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_HTML_TreeTest {
            get {
                return ResourceManager.GetString("FileName_HTML_TreeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W3C_example.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_HTML_W3C_Example {
            get {
                return ResourceManager.GetString("FileName_HTML_W3C_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test1.ini に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_INI_TestFile1 {
            get {
                return ResourceManager.GetString("FileName_INI_TestFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ..\..\..\..\..\Local\FCIV\fciv.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOCAL_FilePath_FCIV {
            get {
                return ResourceManager.GetString("LOCAL_FilePath_FCIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ..\..\..\..\..\Local\MacAddress.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOCAL_FilePath_MacAddressTestFile {
            get {
                return ResourceManager.GetString("LOCAL_FilePath_MacAddressTestFile", resourceCulture);
            }
        }
    }
}
