//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUILDLet.Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUILDLet.Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   HTML content is invalid! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHtmlContentErrorMessage {
            get {
                return ResourceManager.GetString("InvalidHtmlContentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Appropriate End Tag could not be found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHtmlContentErrorMessage_EndTagNotFound {
            get {
                return ResourceManager.GetString("InvalidHtmlContentErrorMessage_EndTagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content of Start Tag starts with \&quot;&lt;!\&quot; and ends with \&quot;/&gt;\&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHtmlContentErrorMessage_InvalidEmptyElement {
            get {
                return ResourceManager.GetString("InvalidHtmlContentErrorMessage_InvalidEmptyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML content ends with &quot;&lt;&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHtmlContentErrorMessage_InvalidHtmlEnd {
            get {
                return ResourceManager.GetString("InvalidHtmlContentErrorMessage_InvalidHtmlEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML content does not start with &quot;&lt;[A-Za-z!]&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHtmlContentErrorMessage_InvalidHtmlStart {
            get {
                return ResourceManager.GetString("InvalidHtmlContentErrorMessage_InvalidHtmlStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Any HTML tag is not included in HTML content. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHtmlContentErrorMessage_NotIncludingAnyTag {
            get {
                return ResourceManager.GetString("InvalidHtmlContentErrorMessage_NotIncludingAnyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is not content of Start Tag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHtmlContentErrorMessage_StartTagEmpty {
            get {
                return ResourceManager.GetString("InvalidHtmlContentErrorMessage_StartTagEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please try without STRICT mode. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHtmlContentErrorMessage_TryNoStrict {
            get {
                return ResourceManager.GetString("InvalidHtmlContentErrorMessage_TryNoStrict", resourceCulture);
            }
        }
    }
}
