//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUILDLet.Utilities.WOL.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUILDLet.Utilities.WOL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon BUILDLet_WOL {
            get {
                object obj = ResourceManager.GetObject("BUILDLet_WOL", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultCloseAfterSend {
            get {
                return ResourceManager.GetString("DefaultCloseAfterSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultHistories {
            get {
                return ResourceManager.GetString("DefaultHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultSendCount {
            get {
                return ResourceManager.GetString("DefaultSendCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultShowDialogAfterSend {
            get {
                return ResourceManager.GetString("DefaultShowDialogAfterSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CloseAfterSend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INI_CloseAfterSend_Key {
            get {
                return ResourceManager.GetString("INI_CloseAfterSend_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Histories に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INI_Histories_Key {
            get {
                return ResourceManager.GetString("INI_Histories_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MacAddressList に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INI_MacAddressList_Key {
            get {
                return ResourceManager.GetString("INI_MacAddressList_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SendCount に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INI_SendCount_Key {
            get {
                return ResourceManager.GetString("INI_SendCount_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShowDialogAfterSend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INI_ShowDialogAfterSend_Key {
            get {
                return ResourceManager.GetString("INI_ShowDialogAfterSend_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WOL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INI_WOL_Section {
            get {
                return ResourceManager.GetString("INI_WOL_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input MAC Address: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputMessageLabelContent {
            get {
                return ResourceManager.GetString("InputMessageLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   20 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaxHistories {
            get {
                return ResourceManager.GetString("MaxHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   255 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaxSendCount {
            get {
                return ResourceManager.GetString("MaxSendCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendButtonContent {
            get {
                return ResourceManager.GetString("SendButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magic Packet [{0}] has been sent {1} time(s) successfully! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WOL.ini に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingFileName {
            get {
                return ResourceManager.GetString("SettingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BUILDLet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingFilePersonalFolderName {
            get {
                return ResourceManager.GetString("SettingFilePersonalFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BUILDLet Utilities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UtilitiesFolderName {
            get {
                return ResourceManager.GetString("UtilitiesFolderName", resourceCulture);
            }
        }
    }
}
