//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUILDLet.Utilities.PInvokeTests.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUILDLet.Utilities.PInvokeTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   api.chm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_ChmHelp_TestFile1 {
            get {
                return ResourceManager.GetString("FileName_ChmHelp_TestFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hhaxref.chm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_ChmHelp_TestFile2 {
            get {
                return ResourceManager.GetString("FileName_ChmHelp_TestFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   htmlhelp.chm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_ChmHelp_TestFile3 {
            get {
                return ResourceManager.GetString("FileName_ChmHelp_TestFile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   htmlref.chm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_ChmHelp_TestFile4 {
            get {
                return ResourceManager.GetString("FileName_ChmHelp_TestFile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Viewhlp.chm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_ChmHelp_TestFile5 {
            get {
                return ResourceManager.GetString("FileName_ChmHelp_TestFile5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BUILDLet.Utilities.chm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName_ChmHelp_UtilitiesHelpFile {
            get {
                return ResourceManager.GetString("FileName_ChmHelp_UtilitiesHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ..\..\..\..\..\Local\HTML Help\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderPath_ChmHelpFile {
            get {
                return ResourceManager.GetString("FolderPath_ChmHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ..\..\..\BUILDLet.UtilitiesHelpDocumentation\Help\ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderPath_UtilitiesHelpFile {
            get {
                return ResourceManager.GetString("FolderPath_UtilitiesHelpFile", resourceCulture);
            }
        }
    }
}
